name: Build

on: [push]

jobs:
  build:

    runs-on: linux-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -H. -Bbuild

    - name: run
      run: ./build/TypeScriptPP -s lua
