name: Check style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install clang-format
      run: brew install clang-format

    - name: Configure
      run: |
        cmake -Htest -Bbuild
        npm install
  
    - name: Check cpp format
      run: cmake --build build --target check-format

    - name: check ts style
      run: npm run check:style