name: Check style

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install clang-format
      run: brew install clang-format

    - name: Configure
      run: |
        cmake -H. -Bbuild
        npm install
  
    - name: Check cpp format
      run: cmake --build build --target check-format

    - name: check ts style
      run: npm run check:style